
[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
decorations = "None"
opacity = 0.9

[general]
import = ["/home/kabirz/.config/alacritty/theme.toml", "/home/kabirz/.config/alacritty/keymaps.toml"]
